### ISSUE TITLE
Operator pod in CrashLoopBackOff with segfault in runtime.go

### ISSUE THREAD

**Issue by cwilkers** [openshift-kni/performance-addon-operators#92]
Output follows:

```I0221 22:59:14.535851       1 main.go:47] Operator Version: 0.0.1
I0221 22:59:14.535926       1 main.go:48] Go Version: go1.13.5
I0221 22:59:14.535931       1 main.go:49] Go OS/Arch: linux/amd64
I0221 22:59:14.535945       1 main.go:50] Version of operator-sdk: v0.13.0
I0221 22:59:16.643037       1 main.go:98] Registering Components.
E0221 22:59:23.005157       1 main.go:142] Could not create ServiceMonitor object: servicemonitors.monitoring.coreos.com "performance-operator-metrics" already exists
I0221 22:59:23.005223       1 main.go:150] Starting the Cmd.
I0221 22:59:23.005333       1 leaderelection.go:242] attempting to acquire leader lease  openshift-performance-addon/performance-addon-operators...
I0221 22:59:40.625216       1 leaderelection.go:252] successfully acquired lease openshift-performance-addon/performance-addon-operators
I0221 22:59:41.829084       1 performanceprofile_controller.go:199] Reconciling PerformanceProfile
E0221 22:59:41.829373       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1225 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14bf9a0, 0x23b78f0)
	/go/src/github.com/openshift-kni/performance-addon-operators/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/openshift-kni/performance-addon-operators/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x14bf9a0, 0x23b78f0)
	/root/.gimme/versions/go1.13.5.linux.amd64/src/runtime/panic.go:679 +0x1b2
github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/machineconfig.getIgnitionConfig(0x1689e3a, 0x7, 0xc00094edc0, 0x1687e56, 0x1, 0x168804e)
	/go/src/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/machineconfig/machineconfig.go:195 +0x4d2
github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/machineconfig.New(0x1689e3a, 0x7, 0xc00094edc0, 0x28, 0x23f31c0, 0x0)
	/go/src/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/components/machineconfig/machineconfig.go:85 +0x22b
github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile.(*ReconcilePerformanceProfile).applyComponents(0xc00079e540, 0xc00094edc0, 0x0, 0x1, 0x0)
	/go/src/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/performanceprofile_controller.go:305 +0x74
github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile.(*ReconcilePerformanceProfile).Reconcile(0xc00079e540, 0x0, 0x0, 0xc0004bbdf0, 0xb, 0xc000521cd8, 0xc000348ab0, 0xc000868488, 0x18902e0)
	/go/src/github.com/openshift-kni/performance-addon-operators/pkg/controller/performanceprofile/performanceprofile_controller.go:267 +0x769
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001b2a80, 0x1516b60, 0xc000a0fee0, 0x0)
	/go/src/github.com/openshift-kni/performance-addon-operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x162
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001b2a80, 0x111b800)
	/go/src/github.com/openshift-kni/performance-addon-operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xcb
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0001b2a80)
	/go/src/github.com/openshift-kni/performance-addon-operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000b657c0)
	/go/src/github.com/openshift-kni/performance-addon-operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000b657c0, 0x3b9aca00, 0x0, 0x1, 0xc0005d4120)
	/go/src/github.com/openshift-kni/performance-addon-operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc000b657c0, 0x3b9aca00, 0xc0005d4120)
	/go/src/github.com/openshift-kni/performance-addon-operators/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/src/github.com/openshift-kni/performance-addon-operators/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x328
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb3be32]
```

**Comment by slintes** [comment]
probably fixed in #93 / #96 

if not, please provide your performance profile manifest and reopen, thanks!

/close
